export default {
  chapters: [
    { 
      name: 'family',
      contentBlocks: [
        {
          title: 'One of the first things a therapist asks you when you sit down on that uncomfortable lounge chair is your relationship with your family.',
          copy: [
            'And if you’ve been living in denial long enough to still have avoided therapy, you still get asked that question when you see any type of doctor. This is the go-to question that every professional will ask you when they’re trying to figure out what is wrong with you.',
            'It makes sense why every therapist wants to pry through your family tree. Genetics and family relationships <a href="https://google.com" target="_blank" heavily contribute to your likelihood of having depression</a> because family dynamics form an early foundation for you to base your life perspective and relationships. Stressors during formulative childhood years tend to roll over into adulthood, and soon enough you’re a sad adult sitting on that lounge chair wondering how the hell you got here.'
          ],
          image: '/static/img/chapterOne/one.png',
        },
        {
          floatingCopy: 'My sister, eight years older, indirectly taught me that the less interaction I had with our parents, the better.',
          copy: [
            'When it comes to therapy, I never know how to answer questions about my family. I know these professionals are trying to weed me out, figure out if I have daddy issues, if I was abused, if I wasn’t hugged enough when I was a child. But I had a relatively comfortable childhood. I grew up in a Vietnamese household in the boring suburbs of San Jose, California, where over 30% of the population was Asian. I had seen plenty of kids that dealt with tiger moms, overly controlling dads, and totalitarian environments where grades dictated their worth.',
            'Compared to that, I was lucky. Both of my parents worked full-time, so I had little interaction with them other than the mornings before school and the evenings when they would pass by my room. Our household was a much more casual environment, where I didn’t have to eat dinner with them, talk to them, or follow curfew. That may sound like a lonely dynamic for a child to have, but I never thought of it that way. I was content with just hanging out with my friends afterschool, watching anime with my sister, and spending all of my free time on the computer, which contained an entirely vast universe that brought perspective beyond my little world.',
            'My sister, eight years older, indirectly taught me that the less interaction I had with our parents, the better. She had explosive reactions to everything our parents did. A small annoyance would incite eye-rolling, yelling, and shrieking that would echo around the house. Her contagious anger would immediately turn my attitude from content to sour, as I was quick to take her side and adapt her mannerisms. She refused to address my father as a dad, and we gave him the nickname “That Man” (or, if we were talking to our mother, “Your Husband”)—verbally stripping him of any relation to us.',
            'My understanding as a child was limited to our parents simply being annoying and stupid, so I would talk to them in a brash manner without understanding the source of where all that mimicked anger came from. It wasn’t until middle school when my sister, who was away at college, brought up some of her childhood memories in the middle of a late-night text conversation. She talked about our drunken father stomping down the staircase, spilling knives out of the cabinets and threatening to cut off his fingers. She recalled our mother crying in the car and telling my sister that she wished she could leave him, but couldn’t because of her.',
            'Hearing that story was, obviously, pretty heavy shit for my middle school self. In an ironic twist of fate, the next day, my English teacher gave us an assignment to write an essay about why our dads are our heroes.'
          ],
          image: '/static/img/chapterOne/two.png',
        },
        {
          floatingCopy: 'I learned to kill any desire for material items or luxuries.',
          copy: [
            'My father doesn’t have a drinking problem anymore, and my parents seem to be fine with their marriage now, since my mother often insists to my sister that he’s changed. But other problems surfaced as I grew older. The most prominent was their financial irresponsibility. They spent excessively on giant TV screens and fake designer bags while my sister would criticize any of my desires to buy something, harping that we didn’t have enough money for that. They would take us on trips to Las Vegas and sit at the slot machines for hours while we stayed in hotel rooms, bored out of our minds. By the time I went to college, my mother told me to take out every single loan the university offered throughout all four years because we couldn’t afford tuition. But every time I visited home, my grandmother would privately rant and cry to me about how much money they’d blown away, taking weekend trips to casinos and draining their bank accounts.',
            'Pathological gambling and drinking shouldn’t be a surprise to non-white families, since these addictions are prevalent for many ethnic minorities. In fact, Southeast Asian and Cambodian refugees in the U.S. have <a href="https://google.com" target="_blank">reported rates of gambling disorder as high as 59%</a>. Whether these vices are due to acculturative stress or culturally normalized traditions, I don’t know. What I do know is that money was a limiting supply that was, in my family, constantly running out.',
            'Watching their financial indiscretions throughout the years made me feel incredibly guilty every time I spent money, because I felt like I’d never have enough. I learned to kill any desire for material items or luxuries. I never asked for gifts. I skipped graduation trips because I didn’t want to spend more money. When I had to buy things out of necessity, like toiletries and clothes, I’d purchase the cheapest price available. And if I woke up past noon on a weekend, I saw it as good news that I was able to save a few dollars by skipping meals and not using electricity.',
            'I was, and still am, extremely self conscious about my money, always feeling like I needed to save as much as possible or else our parents would spend it all.'
          ],
          image: '/static/img/chapterOne/three.png'
        },
        {
          floatingCopy: '“Parents are supposed to be the ones who take care of you and look out for you,” he said, “but instead yours did this.”',
          copy: [
            'In some way, my intuition was correct. During my junior year of college, I got a text from my sister in the midst of her jarring discovery: she was $20,000 in debt because our parents had been opening cards under her name and maxing it out for the past 10 years. She confronted them about it, but they reacted defensively, either pretending like they were going to pay it off eventually or telling her to stop bringing it up because “money doesn’t matter”. For the next few days, my sister and I texted and called each other to figure out what to do about the debt and dishonesty. Ultimately, she paid it off herself without filing any fraud or police reports. She would repeat this twice for the next few months when we found out out that they opened a few more cards.',
            'By the third time it happened, my sister felt more helpless than ever, crying over the phone to me that there was no way she could stop them. After all, identity fraud is too easy when the criminals in question are the only other people in the world who know your birthday and social security. I kept telling her to report them to the police and cut ties completely, but she never did. As a single doctor in her 30s, who lived alone and hated her job, she explained that she had nothing else in her life but them.',
            'That became one of the integral differences between my sister and me. While she still remains attached to our parents, visiting them every other weekend and even spending vacations with them, I gradually began to distance myself further from the family. I moved across the country and stopped taking their calls and responding to their texts. Whenever I was back in town, I only used their house as a free AirBnB, and spent most of my time and energy among friends instead. I was content with this arrangement to reap the benefits of free housing within my hometown without the emotional labor of parents who truly didn’t give a fuck about robbing you.',
            'When I found out that my father opened a card under my name and maxed it out for over two years, I took out any emotion from the unsurprising discovery and jumped straight to the process. I spent the next few days filing identity fraud reports, setting up alerts, and talking to 5 different police stations. Like every process involving the police and government, the whole ordeal was stressful and longwinded. But by the time I was done, I sent a formal yet thinly-veiled threatening email to my parents explaining in detail about the reports, the police, and how I didn’t have any shred of guilt about suing them if they repeated this offense.',
            'It was cold and calculated, and it was my way of dealing with the situation responsibly and efficiently. I talked to a coworker about it later, and as a father of two children who were around the same age as me, he told me that he couldn’t imagine how a parent could do something like this to their children.',
            '“Parents are supposed to be the ones who take care of you and look out for you,” he said, “but instead yours did this.” For the first time, and only time, I started crying.'
          ],
          image: '/static/img/chapterOne/four.png'
        },
        {
          floatingCopy: 'No family is the same, but I’ve found that there is something uniquely dysfunctional about many Asian families.',
          copy: [
            'The results were inconsequential: my mother ignored my email, following her usual pattern of avoiding problems and sweeping them under the rug. My father formed a half-assed apology, feigning innocence that he forgot to cancel the card, even though the statements showed he had been using it every month until I canceled it. As always, I didn’t reply to them and moved on with the rest of my life. I was simply glad that I had scared them off. My sister, on the other hand, still visits them every other weekend.',
            'Although my sister thinks she needs a family, I know that I don’t. Since childhood I’ve been used to sharing meals by myself, and for years I’ve taking care of myself financially, physically, and mentally. The only time I notice that missing piece where a family should be is when the holiday seasons roll along: all the streets are closed down, social feeds become cluttered with photos of delicious food, and I usually sleep the whole day away until the world returns back to its regular routine. To me, that is enough.',
            'No family is the same, but I’ve found that there is something uniquely dysfunctional about many Asian families. It’s something that I can’t explain very easily, but is innately understood from one Asian to another. Research has found that <a href="https://google.com">Asian Americans have a 17.3% chance of developing a psychiatric disorder</a> in their lifetimes, but are 33% less likely to seek help or even admit to having them compared to white Americans. This is another reason why answering any family-related questions is difficult for me to do and for doctors to gauge, because even if we had any issues throughout the family tree, I wouldn’t know about them.',
            'When I think about the quietly dysfunctional nature of Asian-American families, I am reminded of a serio-comic performance called <a href="https://google.com" target="_blank">Wong Flew Over the Cuckoo’s Nest</a>. In that performance, comedian Kristina Wong opens up her skit with a conflict that she is trying to solve: the inexplicably high rates of Asian-American women committing suicide. She takes a dark yet tongue-in-cheek approach, singing to the tune of We Are the World: "We are complete... we are perfect... we are the ones who keep killing ourselves but let\'s start smiling."'
          ],
          image: '/static/img/chapterOne/five.png'
        },
        { 
          floatingCopy: 'I am a product of my family’s sacrifices with the consequences of loneliness and insolation.',
          copy: [
            'U.S.-born Asian-American women have a <a href="https://google.com" target="_blank">higher lifetime rate of suicidal thoughts</a> (almost 16%) than that of the general U.S. population (13.5%). Hearing the numbers, I wasn’t surprised. This fact is shocking but intimately familiar to me at the same time. It is something that I can innately understand, even if my lifestyle is vastly different from each Asian girl out there who has considered jumping off a bridge or buying a loaded gun.',
            'I am sure that there are several complicated factors that contribute to why families, especially ethnic minorities, deal with alcoholism, gambling addictions, and abuse. I know that mine have faced unfathomable trauma from poverty and immigrating to the States. Certainly, that intergenerational trauma has trickled down the family tree and taken form as our different vices. If I put in the time and effort, I could find out my parents’ stories and try to understand why they are the way that they are. But to be honest, and to probably give an unsatisfying reaction to readers, I don’t care.',
            'It is my personal belief that I am not obligated to learn about my family’s history, keep in touch with them, or take care of them financially or emotionally. It is not my responsibility to forgive them for their behavior, or learn about their past in order to understand their behavior. Some people may disagree. But I think that is because that is how they would define getting closure. That is not how I define it. I am not interested in spending my energy trying to fix them or learn from them more than what I have already learned by existing.',
            'I am a product of my family’s sacrifices with the consequences of loneliness and isolation. The intimate relationships I form today hold heavier weight on me than the average person, because I had not been able to form those emotional connections early on. I am unable to enjoy luxuries—by which I define those as meals over $20 and furniture that was not at the top of the ‘lowest price’ filter on Amazon—without being guilt-ridden over losing money. The difference between my pragmatic decisions and others’ is that people have appropriated “minimalism” as a trend, while I use “minimalism” as a way to clutch onto my learned frugality like a lifejacket.',
            'But I take pride in my ability to be independent. I‘ve moved across the country to live on my own. I expect to finish paying off my $70,000+ student loans before 2020. And I’ve learned to survive and exist without the safety net of family. Rather than live in their shadows and reap what they sow, I would rather move forward to forge my own life.'
          ]
        }
      ]
    },
    {
      name: 'love',
      contentBlocks: [
        {
          title: 'For as long as I remember, I have always been a romantic.',
          floatingCopy: 'In the fictional world, obstacles are only there to thicken the plot.',
          copy: [
            'I grew up watching anime and exclusively consumed shoujo manga: stories aimed at the female target-demographic readership, often with a focus on romantic relationships and emotions. They starred wide-eyed girls who fell in love with the handsome, young men that rescued them (or vice versa, if the stories were more progressive). It didn’t matter if they were a modern-day student in high school or a heroine of an epic fantasy; no matter what, they always found a boy who loved them so much that my 12-year-old self’s heart would flutter just at the thought if it. How wonderful it was, this phenomenon that someone in the world could care so purely and deeply for you.',
            'I spent years devouring media that taught little girls everywhere that receiving a boy’s care and affection was the ultimate happy ending. Maybe my affinity for these narratives was what made me so naive. It’s easy to ignore red flags for the sake of fulfilling the romanticized stories you grew up with. Rom-coms push out grand gestures as unequivocal signs of true love, <a href="https://www.theatlantic.com/health/archive/2016/02/romantic-comedies-where-stalking-meets-love/460179/" target="_blank">subconsciously training us to accept problematic behavior</a> like stalking and possessiveness as noble pursuits for romance. In the fictional world, obstacles are only there to thicken the plot. In the end, love conquers all.',
            'When I dated my first boyfriend in freshman year of college, I fell for him fast and hard. We met during the first week of freshman year when I visited a dorm lounge. The university didn’t have enough space to accommodate all incoming freshmen, so I had been moved into a lonely studio apartment and longed for the communal dorm experience. He invited me to all of their socials, and I was happy whenever his dorm friends claimed that they had “adopted” me. For the first time, I felt included.',
            'It was easy for me to become attracted to him because of the special attention that he paid to me. Growing up, hardly any boy talked or treated me differently than a piece of wallpaper. But this one would hold my hand when we ice-skated, walk me home to my apartment every night, and compliment how beautiful I looked. One night before an 8 AM class, we stayed up until 5 AM just talking and holding hands. For our first date, he visited my apartment with a bouquet of roses and cooked beef stroganoff for just the two of us.',
            'I was completely swept off my feet. This was all that I had wanted: grand, romantic gestures from someone who could make me feel special. This was my shoujo story. It had everything: the meet-cute, the big moments, the shyness and awkward fumbles of first love. And he was so romantic and chivalrous—how could dating a guy as nice as him go wrong?'
          ],
          image: '/static/img/chapterTwo/one.png',
        },
        {
          title: '',
          floatingCopy: 'There were core differences in our values and how he didn’t see me as a human being.',
          copy: [
            'But as quickly as we started dating, so did the problems come to surface. Two months into the relationship, something as simple as two awkward-looking kids holding hands evolved into a tumultuous, rollercoaster relationship where we would fight every other day. As we stayed together for the next two years, I began to realize that, when I looked past all the flower bouquets and cheesy cards, this person didn’t make me happy. I saw his gestures as characteristics of him being a nice person, when in actuality, he wasn’t nice at all. My rose-colored glasses had blocked all the warning signs of a relationship where I would soon feel worthless, trapped, and devastatingly miserable.',
            'There were so many red flags that I should have detected early on, but didn’t because it was my first relationship. He would make fun of me for being a feminist, inciting groans and shaking heads from his friends. “I can’t believe I’m dating a feminist,” he’d say, as if it were a ridiculous phenomenon, then pretended to snore as I explained my beliefs. Already that should have indicated there were core differences in our values and how he didn’t see me as a human being.',
            'But there were other issues, too. When he visited my apartment and saw a pair of contact lenses on the sink, he interrogated me on whether another guy slept here or not. When he saw photos of me smiling next to a male colleague named Jackson, he drew a crying face on a wall at his construction job, wrote “ASSHOLE JACK” underneath it, and smashed the wall with his sledgehammer. His jealousy extended beyond me being around other men, as he would also become resentful if I had any form of success. When I excitedly told him about landing my first internship, he questioned if I really knew what I was doing and said I was too much of a “clueless little girl”.',
            'He was so insecure with himself that he couldn’t stand seeing me doing any better than him, and as a result, would often talk me down and make me feel worthless and stupid. He also hated feeling like the bad guy, so every time I expressed sadness or hurt, he would blow up and get angry that I was putting him at fault. He blamed my negativity for ruining our relationship.'
          ],
          image: '/static/img/chapterTwo/two.png',
        },
        {
          title: '',
          floatingCopy: 'I feared that he was right: that my sadness was a horrible flaw, rendering us incapable of being happy together.',
          copy: [
            'Because I was so deeply entrenched in my depression, I feared that he was right: that my sadness was a horrid flaw, rendering us incapable of being happy together like we should be. Why was I making everything so difficult for us? Why was my misery such a hassle? I wished several times that I could be a robot, just so that I couldn’t feel anything anymore. Just so that life could be easier.',
            'Disavowing my true unhappiness out of fear that it would only instigate conflict was something that this relationship trained me to do. The emotional compartmentalization was a result of gaslighting, where my partner’s refusal for accountability manipulated my brain into inheriting the blame. I would swallow his poison for the next two years.',
            'I learned to contain my sadness in order to prevent our fights from escalating. Somehow, though, it always would. Sadness was too difficult to hide when it seemed to embody me completely. He made me cry so much that I would wander around campus like a ghost afterward, devoid of joy or personality or humor. I felt like I was an empty shell of who I used to be, swollen eyes and broken parts and all. I was no longer the funny girl who loved reading shoujo manga and writing fantasy novels—I was just somebody who was sad all the time.',
            'When we broke up, it was the hardest thing ever. Which I know sounds stupid, because it had been such a terrible relationship in the first place. But it had been a devastating blow to me just because the aftermath demonstrated how lonely I was. I didn’t have anything else. All of my friends had come from his social circle, so I lost all of them with him. I had no close friends or family to give perspective or advice. I realized that my estranged relationship with my family left me longing for emotional care that hadn’t been provided until I met him. Even though he was wrong and twisted, he had been the only one there for me. Now he was gone, and all I could think was: Nobody else will care for you the way that he did.'
          ],
          image: '/static/img/chapterTwo/three.png',
        },
        {
          title: '',
          floatingCopy: 'How can you forgive yourself when you can’t even acknowledge the hurt you’ve caused?',
          copy: [
            'Six months after our relationship ended, I received an email in my inbox from him. We hadn’t been in touch since then, but I was still distraught by the emotional turmoil he had left behind. There was still heart-pounding fear that I would run into him whenever I walked around campus, and seeing any classmate wearing a sweatshirt with his fraternity symbols would make me feel sick to my stomach. I blocked him on social media because looking at any pictures of him would immediately make me feel unsafe, unwell, and remind me that I was not okay. When I received his letter, I felt all of those things at once.',
            'His email was framed as an apology letter—at least, it started off with those stated intentions. The rest was written in such a questionable way where he must have performed some mental olympics to justify it as an apology. He apologized for not being more patient with my insecurities and my jealousy issues. Each paragraph talked about a different flaw I had that he should have reacted better to. I wrote him a response that chewed him out for the hypocrisy, but he never responded. When we crossed paths a few months later, he continued avoiding the blame when I brought it up, asked not talk about the past anymore, and even proclaimed “I’ve learned to forgive myself”. When I asked if he actually read my response email, he said that he “couldn’t bear to read it”.',
            'How can you forgive yourself when you can\'t acknowledge the hurt you’ve caused? Ultimately, that letter had been written to relieve his own conscience. Engaging him any further would be frustrating and futile. Since then, I have never spoken to him again.',
            'After the breakup, I became heavily involved in sports and weightlifting by joining the dragon boat team halfway through college. Dragon boat is a racing watersport that consists of 20 people on one boat, paddling in synchronization from as long as 2000 meters to the finish line. This team-oriented sport was revolutionary in improving my life by introducing both fitness and friendship in a time when I needed it most. I loved my new lifestyle, and I met some of my best friends who I still talk to today. I felt like I could trust everyone on the team during this new chapter—and that’s why, when the captain started flirting with me, I put all of my trust in this new prospect of a better relationship too.',
            'If this were a more traditional story, right here would be the part where I tell you that I eventually found love. This is the part where I would talk about how it was kind, and nurturing, and fulfilling. This is when I have an epiphany that all of that pain would lead me to the right person in the end.',
            'This is what actually happened: I reciprocated my captain’s flirtations.',
            'We connected.',
            'I opened up about my struggles and depression to him. ',
            'He said he would always be there for me.',
            'We slept together.',
            'His texts became sporadic.',
            'I asked where he went.',
            'He replied, “I don’t have time to talk to you.”',
            'He got back together with his ex.',
            'I missed the red flags again.'
          ],
          image: '/static/img/chapterTwo/four.png',
        },
        {
          title: '',
          floatingCopy: 'I misplaced love onto irresponsible people. I realize now that I should have placed it on myself first.',
          copy: [
            'I fell into a deeper depression. Started taking Prozac. Quit the team. Bumped Prozac up to 20mg. Hated myself for being stupid. Bumped Prozac up to 40mg. Hated myself for being unlovable. Bumped Prozac up to 60mg. Hated, hated, hated loneliness.',
            'I don’t know any exact moment when things started getting better. All I know is that it eventually did. The meds worked. I became busier with friends. I discovered design, and from then on, I threw all of my time into it: learning the programs, starting side projects, and putting energy into a career path I could be excited about.',
            'I found so much fulfillment in design because it provided both a creative outlet and a career path that I could continuously work towards. Relationships were too complicated and dependent on external factors (human beings) to be relied on for happiness. On the other hand, work was something that I could control, and if I worked hard enough, I could achieve great things out of it. Design filled a hole in my life where I could finally feel accomplished and valuable. That drive has not gone away even to this day.',
            'After distancing myself from the tumultuous world of dating and relationships, I feel silly for relying so much of my happiness and self-worth on other people. Everybody goes through terrible relationships, and emotionally abusive relationships are unfortunately more common than you think. I realize the real reason why these fallouts had affected me so much: I had been searching for the emotional connections and support that had been absent from my family and lack of friendships.',
            'By default, a family is the first source of safety, warmth, and happiness. Friendship becomes the second source as people traverse through life, forging strong bonds with other people that border on familial. I didn’t have either of those relationships in my life. As a result, I ended up funneling all those desires for emotional connections into men who were too selfish and too young to grasp something so delicate.',
            'I misplaced love onto irresponsible people. I realize now that I should have placed it in myself first. People will come and go in life. Their feelings will change, and there is always a chance they will leave. The only person that you’re stuck with for the rest of your life is yourself. So take ownership for yourself.',
            'I’ve learned that being alone is better than being with someone who isn’t right for me. <a target="_blank" href="https://www.forbes.com/sites/quora/2018/05/03/research-shows-bad-relationships-can-also-mean-bad-health/">Toxic relationships take a toll on both your mind and body</a>—so while it may fulfill that hole of loneliness and self-loathing for now, the depression will become exacerbated in the long run when you depend your happiness on another person.',
            'I’ve owned up to my independence so extremely that I haven’t been in a relationship since then. Even as I continue to be single for years, I don’t feel any pressure to find a partner or go on dates. It’s not that I’ve closed myself off from relationships. It’s just that my priorities in life have changed.',
            'I still love reading shoujo—those stories remain as a guilty pleasure, especially as a break from the weight of reality and adulthood. But that’s all these stories are: escapism. A fantasy that has been coveted from childhood nostalgia. It’s an indulgent hobby that stems from a time in my life when I didn’t know there were so many other things in the world to be excited about—that love can take on different forms besides romance, like love for work, for platonic relationships, and for oneself.',
          ],
          image: '/static/img/chapterTwo/five.png',
        },
        {
          title: '',
          floatingCopy: '',
          copy: [
            'The last story that I want to share comes from when a girl I’d never met messaged me. She explained that she had dated my ex and was now struggling with the subsequent depression, insecurity, and extinguished sense of self-worth. She was reaching out to me for help. I stayed up talking to her all night until 2 AM, trying to support her as best as I could with my own perspective. We’ve become friends since then, and although it angers me that he continued to hurt other people after our relationship, I’m glad that I can use this experience to help others who also struggle with toxic relationships and lack of self-worth. My pain did not lead me to any greater, truer love with another partner, but it has taught me to be more empathetic to others and compassionate to myself.',
            'Love can be defined in other ways. I’m still expanding my definition of it.'
          ],
        }
      ]
    }
  ]
}